export default  {
products :[
  {
    id: 1,
    name: "Nike Full-Zip Hood Men's Workout Sweatshirt",
    category: "Shirts",
    image: "./images/product-1.jpg",
    price: 49.99,
    brand: "Nike",
    rating: 4.7,
    numReviews: 210,
    countInStock: 75,
  },
  {
    id: 2,
    name: "Adidas Performance T-Shirt",
    category: "Shirts",
    image: "./images/product-2.jpg",
    price: 25.99,
    brand: "Adidas",
    rating: 4.6,
    numReviews: 150,
    countInStock: 120,
  },
  {
    id: 3,
    name: "Under Armour Men's Joggers",
    category: "Pants",
    image: "./images/product-3.jpg",
    price: 39.99,
    brand: "Under Armour",
    rating: 4.5,
    numReviews: 85,
    countInStock: 100,
  },
  {
    id: 4,
    name: "Levi's 501 Original Fit Jeans",
    category: "Pants",
    image: "./images/product-4.jpg",
    price: 59.99,
    brand: "Levi's",
    rating: 4.4,
    numReviews: 230,
    countInStock: 80,
  },
  {
    id: 5,
    name: "Columbia Women's Arcadia II Jacket",
    category: "Jackets",
    image: `./images/product-5.jpg`,
    price: 69.99,
    brand: "Columbia",
    rating: 4.8,
    numReviews: 95,
    countInStock: 60,
  },
  {
    id: 6,
    name: "Patagonia Men's Better Sweater",
    category: "Sweaters",
    image: "./images/product-6.jpg",
    price: 89.99,
    brand: "Patagonia",
    rating: 4.9,
    numReviews: 180,
    countInStock: 45,
  },
  {
    id: 7,
    name: "The North Face Thermoball Eco Vest",
    category: "Vests",
    image: "./images/product-7.jpg",
    price: 129.99,
    brand: "The North Face",
    rating: 4.7,
    numReviews: 110,
    countInStock: 50,
  },
  {
    id: 8,
    name: "Nike Dri-FIT Running Shorts",
    category: "Shorts",
    image: "./images/product-8.jpg",
    price: 29.99,
    brand: "Nike",
    rating: 4.6,
    numReviews: 130,
    countInStock: 150,
  },
  {
    id: 9,
    name: "Ralph Lauren Polo Shirt",
    category: "Shirts",
    image: "./images/product-9.jpg",
    price: 79.99,
    brand: "Ralph Lauren",
    rating: 4.8,
    numReviews: 170,
    countInStock: 90,
  },
  {
    id: 10,
    name: "Tommy Hilfiger Men's Bomber Jacket",
    category: "Jackets",
    image: "./images/product-10.jpg",
    price: 119.99,
    brand: "Tommy Hilfiger",
    rating: 4.7,
    numReviews: 60,
    countInStock: 40,
  },
]
} 



